# Generated by Django 4.1.7 on 2023-04-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
        migrations.RenameModel(
            old_name='Supermercados',
            new_name='Supermercado',
        ),
    ]
